package com.jini.indicator.plugin

object ProguardRuleGenerator {

    @Suppress("UNCHECKED_CAST")
    fun generate(
        includes: List<Map<String, Any>>,
        excludes: List<Map<String, Any>>
    ): String = buildString {
        appendLine("# Auto-generated by processing-indicator-aop-plugin")
        appendLine()

        includes.forEach { rule ->
            when {
                rule["package"] != null ->
                    appendLine("-keep class ${rule["package"]}.** { *; }")
                rule["class"] != null -> {
                    val methods = rule["methods"] as? List<String> ?: emptyList()
                    if (methods.isEmpty()) {
                        appendLine("-keep class ${rule["class"]} { *; }")
                    } else {
                        appendLine("-keepclassmembers class ${rule["class"]} {")
                        methods.forEach { appendLine("    *** $it(...);") }
                        appendLine("}")
                    }
                }
            }
        }

        appendLine()
        appendLine("# SDK internals")
        appendLine("-keep class com.jini.indicator.** { *; }")
        appendLine("-keep class okhttp3.OkHttpClient\$Builder {")
        appendLine("    public okhttp3.OkHttpClient\$Builder addInterceptor(okhttp3.Interceptor);")
        appendLine("    public okhttp3.OkHttpClient build();")
        appendLine("}")
        appendLine("-keep class java.net.URL { public java.net.URLConnection openConnection(); }")
    }
}
